# Generated by Django 3.0 on 2020-02-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbieapp', '0002_customer_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
