# Generated by Django 2.2.7 on 2019-11-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayneapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Customer',
        ),
    ]
