# Generated by Django 2.2.7 on 2019-11-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayneapp', '0002_auto_20191129_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='version',
            field=models.TextField(default='v1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='version',
            field=models.TextField(default='v1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='version',
            field=models.TextField(default='v1'),
        ),
    ]
